---
#
# Ansible requirements
# Install with: ansible-galaxy install -r requirements.yml
#
- src: geerlingguy.repo-epel
- src: geerlingguy.repo-remi
- src: andrewrothstein.terraform
# - src: geerlingguy.php
# - src: geerlingguy.composer
# - src: geerlingguy.docker
