---
#
# Ansible requirements
# Install with: ansible-galaxy install -r requirements.yml
#
- src: cmprescott.chrome
- src: geerlingguy.composer
- src: geerlingguy.redis
- src: geerlingguy.memcached
- src: stephdewit.nvm
- src: andrewrothstein.terraform
- src: geerlingguy.docker
